dist: bionic
language: python
python:
  - "3.8"

install:
  - pip install nbfancy

script:
  - nbfancy render
  - nbfancy html --include_slides

deploy:
  provider: pages
  repo: JDBetteridge/GenX-Exascale-Workshop
  target-branch: gh-pages
  local-dir: gh-pages/html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.8
